### ISSUE TITLE
Dashboard page 

### ISSUE THREAD

**Issue by SundayBraid** [Sinyks/STI-UnsecureMailApp#5]
page where a user can see his messages

### Tasks

- [x] message list printed on screen sorted on received date 

#### new message

- [x] button for new message
- [x] Modals for new message
- [x] form for new message

#### received messages

- [x] button show content
- [x] modal show content

- [x] button delete message
- [x] modal delete message

- [x] button answer message
- [x] modal answer message
- [x] form answer message
