### ISSUE TITLE
User Administration CRUD

### ISSUE THREAD

**Issue by SundayBraid** [Sinyks/STI-UnsecureMailApp#7]
Fonction/for that allow admin to Create/modify/delete users
Done in fake action php pages

### Tasks

- [x] delete_user_action
- [x] create_user_ action
- [x] update_user_action
